### ISSUE TITLE
Denoising with wavelet transform

### ISSUE THREAD

**Issue by danizil** [timothyyu/wsae-lstm#12]
I've been thinking about the data leakage from the wavelet transform, not sure how to apply it to a live data stream. Denoise with the same modes? Scaling has a similar problem...
I think I'll try building the denoising into the AE: fitting the noisy (or even raw) data with the scaled denoised data on the other side. Maybe its a bit voodoo, but it's one of the main usages of AEs  . What do you think?

**Comment by timothyyu** [comment]
I believe the phase goes along the lines of something like this:
"There is more than one way to skin a cat"

Thus, there are multiple different approaches to take in applying a wavelet transform to a live stream of data (streaming/online model) vs. a batch model. 

I'd say it's worth testing or trying out. The wavelet transform is a complex component by itself - combined with other machine learning/deep learning layers, the complexity overall exponentially goes up depending on how you have your pipeline setup/constructed.

**Comment by timothyyu** [comment]
duplicate/directed related to https://github.com/timothyyu/wsae-lstm/issues/6
